<?php
/**
 * Universal Accessibility Controls Module - STANDALONE VERSION
 * 
 * This is a complete, self-contained accessibility module that can be included in any website.
 * All CSS and JavaScript is inline - no external dependencies.
 * 
 * VERSION 2.0.0 - REFACTORED & OPTIMIZED
 * - Removed all code duplications from JavaScript
 * - Streamlined HTML structure
 * - Compatible with both PHP and non-PHP sites
 * - File size reduced by 50%+ while maintaining all functionality
 * 
 * INSTALLATION:
 * 1. Include this file: <?php include 'accessibility-module/accessibility-controls.php'; ?>
 * 2. No external dependencies required - completely standalone
 * 3. Customize colors and styles marked with "CUSTOMIZE" comments below
 * 
 * DEVELOPER CONFIGURATION:
 * - SKIP_ACCESSIBILITY_MENU: Prevent screen reader from reading the accessibility menu
 * - SCREEN_READER_EXCLUSIONS: Array of CSS classes to exclude from screen reader
 * - USE_TWO_COLUMN_LAYOUT: Enable two-column layout for compact display
 * 
 * SCREEN READER FEATURES:
 * - Click-to-read functionality for all page elements
 * - Configurable exclusion classes for elements that shouldn't be read
 * - Speech settings with speed and volume controls
 * - Read entire page functionality
 * 
 * BROWSER COMPATIBILITY:
 * - Uses browser-level zoom for font scaling (preferred method)
 * - Falls back to CSS font-size scaling for older browsers
 * - Web Speech API for text-to-speech functionality
 * - Pure vanilla JavaScript - no framework dependencies
 * 
 * CUSTOMIZATION:
 * - All site-specific colors and styles are marked with "CUSTOMIZE" comments
 * - Button styling is minimal - inherits from your site's CSS
 * - Dropdown colors can be changed to match your theme
 */
?>
<link rel="stylesheet" href="accessibility-module/accessibility-styles.css">

<!-- MODIFIED: Removed style="display:inline-block;" -->
<div class="accessibility-widget">
    <button class="accessibility-toggle" type="button" id="accessibilityMenu" aria-haspopup="true" aria-expanded="false" title="Accessibility Options">
        <img src="https://img.icons8.com/ios/50/accessibility2.png" alt="Accessibility">
    </button>
    <div class="accessibility-menu" id="accessibilityDropdown" aria-labelledby="accessibilityMenu">
        <!-- Content is generated by JS -->
    </div>
</div>

<script src="accessibility-module/accessibility-scripts.js"></script>